/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import com.clinicahospital.connection.*;
import com.clinicahospital.pessoas.Contas;
import gui.VerificaMensagens.Verifica;
import gui.VerificaMensagens.Verificando;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Weleson
 */
public class Tela_login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_entrar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        campo_login = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        icone1 = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_entrar.setBackground(new java.awt.Color(86, 131, 176));
        botao_entrar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_entrar.setForeground(new java.awt.Color(255, 255, 255));
        botao_entrar.setText("Entrar");
        botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 150, 50));

        campo_login.setBackground(new java.awt.Color(255, 255, 255));
        campo_login.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_login.setText("Login");
        campo_login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_loginMouseClicked(evt);
            }
        });
        getContentPane().add(campo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 350, 40));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Source Code Pro", 0, 20)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 350, 40));

        icone1.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 20)); // NOI18N
        icone1.setForeground(new java.awt.Color(86, 131, 176));
        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-2.png"))); // NOI18N
        icone1.setText("HAE");
        getContentPane().add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 70));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 51, 51));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Usuário.png"))); // NOI18N
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 170, 160));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vyghyjkghkghk.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarActionPerformed
        ContasManager contasLogin = new ContasManager();
        Contas conta = new Contas();
        conta.setLogin(campo_login.getText());
        conta.setSenha(jPasswordField1.getText());
        boolean podeEntrar = contasLogin.autenticar(conta);
        conta.setNivel_acesso(contasLogin.getNivel_acesso());
        int perms = conta.getNivel_acesso();
        System.out.print(perms);
        if(podeEntrar){
            Tela_Menu menu = new Tela_Menu(perms);
            menu.setVisible(true);
            dispose();
            //Verifica notification = new Verifica(String.valueOf(campo_login.getText()));
            Verificando notification = new Verificando(String.valueOf(campo_login.getText()));
            Thread notifications = new Thread(notification);
            notifications.start();
        }
    }//GEN-LAST:event_botao_entrarActionPerformed

    private void campo_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_loginMouseClicked
        campo_login.setText("");
    }//GEN-LAST:event_campo_loginMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_login;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel icone1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
