/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import com.clinicahospital.connection.*;
import com.clinicahospital.pessoas.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Weleson
 */
public class Tela_cadastro_secretaria extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_cadastro_secretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastrar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        campo_sobrenome = new javax.swing.JTextField();
        campo_telefone = new javax.swing.JTextField();
        campo_senha = new javax.swing.JTextField();
        icone1 = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastrar.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastrar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 150, 50));

        campo_nome.setBackground(new java.awt.Color(255, 255, 255));
        campo_nome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_nome.setText("Nome");
        campo_nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, 40));

        campo_sobrenome.setBackground(new java.awt.Color(255, 255, 255));
        campo_sobrenome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_sobrenome.setText("Sobrenome");
        campo_sobrenome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 350, 40));

        campo_telefone.setBackground(new java.awt.Color(255, 255, 255));
        campo_telefone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_telefone.setText("Telefone");
        campo_telefone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 350, 40));

        campo_senha.setBackground(new java.awt.Color(255, 255, 255));
        campo_senha.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_senha.setText("Senha");
        campo_senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 350, 40));

        icone1.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 20)); // NOI18N
        icone1.setForeground(new java.awt.Color(86, 131, 176));
        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-2.png"))); // NOI18N
        icone1.setText("HAE");
        getContentPane().add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 70));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 51, 51));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Secretário.png"))); // NOI18N
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, 160));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vyghyjkghkghk.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed

            System.out.println("1");
            PessoaManager secretariaCad = new PessoaManager();
            Pessoa secretaria = new Pessoa();
            secretaria.setNome(campo_nome.getText());
            secretaria.setSobrenome(campo_sobrenome.getText());
            secretaria.setTelefone(campo_telefone.getText());
        try {
            secretariaCad.inserir(secretaria);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("1");
            ComandosManager comando = new ComandosManager();
            Pessoa paux = new Pessoa();
            paux = comando.selecionar(secretaria.getTelefone());
            System.out.println(paux.getNome());
            Contas conta = new Contas();
            conta.setLogin(Integer.toString(paux.getId()));
            conta.setId_conta(paux.getId());
            conta.setSenha(campo_senha.getText());
            ContasManager contas = new ContasManager();
        try {
            contas.cadastrar(conta);
        } catch (SQLException ex) {
            Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botao_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro_secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_senha;
    private javax.swing.JTextField campo_sobrenome;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel icone1;
    // End of variables declaration//GEN-END:variables
}
