/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Weleson
 */
public class Tela_Pessoa extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Pessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastrar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        campo_sobrenome = new javax.swing.JTextField();
        campo_telefone = new javax.swing.JTextField();
        campo_endereco = new javax.swing.JTextField();
        campo_sintomas = new javax.swing.JTextField();
        campo_nascimento = new javax.swing.JTextField();
        campo_plano1 = new javax.swing.JTextField();
        campo_crm = new javax.swing.JTextField();
        campo_nivel = new javax.swing.JTextField();
        icone1 = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastrar.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastrar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastrar.setText("Cadastrar");
        getContentPane().add(botao_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 150, 50));

        campo_nome.setBackground(new java.awt.Color(255, 255, 255));
        campo_nome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_nome.setText("Nome");
        campo_nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 350, 40));

        campo_sobrenome.setBackground(new java.awt.Color(255, 255, 255));
        campo_sobrenome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_sobrenome.setText("Sobrenome");
        campo_sobrenome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 350, 40));

        campo_telefone.setBackground(new java.awt.Color(255, 255, 255));
        campo_telefone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_telefone.setText("Telefone");
        campo_telefone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 350, 40));

        campo_endereco.setBackground(new java.awt.Color(255, 255, 255));
        campo_endereco.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_endereco.setText("Endereco");
        campo_endereco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 350, 40));

        campo_sintomas.setBackground(new java.awt.Color(255, 255, 255));
        campo_sintomas.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_sintomas.setText("Sintomas");
        campo_sintomas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 350, 40));

        campo_nascimento.setBackground(new java.awt.Color(255, 255, 255));
        campo_nascimento.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_nascimento.setText("Nascimento");
        campo_nascimento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 350, 40));

        campo_plano1.setBackground(new java.awt.Color(255, 255, 255));
        campo_plano1.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_plano1.setText("Plano Saúde");
        campo_plano1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_plano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_plano1ActionPerformed(evt);
            }
        });
        getContentPane().add(campo_plano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 350, 40));

        campo_crm.setBackground(new java.awt.Color(255, 255, 255));
        campo_crm.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_crm.setText("CRM");
        campo_crm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_crm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_crmActionPerformed(evt);
            }
        });
        getContentPane().add(campo_crm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 350, 40));

        campo_nivel.setBackground(new java.awt.Color(255, 255, 255));
        campo_nivel.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_nivel.setText("Nível de Acesso");
        campo_nivel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        getContentPane().add(campo_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 350, 40));

        icone1.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 20)); // NOI18N
        icone1.setForeground(new java.awt.Color(86, 131, 176));
        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-2.png"))); // NOI18N
        icone1.setText("HAE");
        getContentPane().add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 70));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 51, 51));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Usuário.png"))); // NOI18N
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, 160));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vyghyjkghkghk.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nomeActionPerformed

    private void campo_crmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_crmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_crmActionPerformed

    private void campo_plano1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_plano1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_plano1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Pessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_crm;
    private javax.swing.JTextField campo_endereco;
    private javax.swing.JTextField campo_nascimento;
    private javax.swing.JTextField campo_nivel;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_plano1;
    private javax.swing.JTextField campo_sintomas;
    private javax.swing.JTextField campo_sobrenome;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel icone1;
    // End of variables declaration//GEN-END:variables
}
