/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Weleson
 */
public class Tela_Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastro = new javax.swing.JButton();
        botao_consulta = new javax.swing.JButton();
        botao_retorno = new javax.swing.JButton();
        botao_agenda = new javax.swing.JButton();
        botao_receita = new javax.swing.JButton();
        botao_atestado = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastro.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastro.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastro.setText("Cadastro");
        getContentPane().add(botao_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 50));

        botao_consulta.setBackground(new java.awt.Color(86, 131, 176));
        botao_consulta.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_consulta.setForeground(new java.awt.Color(255, 255, 255));
        botao_consulta.setText("Consulta");
        getContentPane().add(botao_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 150, 50));

        botao_retorno.setBackground(new java.awt.Color(86, 131, 176));
        botao_retorno.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_retorno.setForeground(new java.awt.Color(255, 255, 255));
        botao_retorno.setText("Retorno");
        getContentPane().add(botao_retorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 150, 50));

        botao_agenda.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda.setText("Agenda");
        getContentPane().add(botao_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, 150, 50));

        botao_receita.setBackground(new java.awt.Color(86, 131, 176));
        botao_receita.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_receita.setForeground(new java.awt.Color(255, 255, 255));
        botao_receita.setText("Receita");
        getContentPane().add(botao_receita, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 150, 50));

        botao_atestado.setBackground(new java.awt.Color(86, 131, 176));
        botao_atestado.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_atestado.setForeground(new java.awt.Color(255, 255, 255));
        botao_atestado.setText("Atestado");
        getContentPane().add(botao_atestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 730, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 150, 50));

        jLabel3.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo.png"))); // NOI18N
        jLabel3.setText("HAE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 60));

        fundo.setForeground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-Inicial.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_agenda;
    private javax.swing.JButton botao_atestado;
    private javax.swing.JButton botao_cadastro;
    private javax.swing.JButton botao_consulta;
    private javax.swing.JButton botao_receita;
    private javax.swing.JButton botao_retorno;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
