/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.clinicahospital.agenda.Agendar;
import com.clinicahospital.connection.AgendaManager;
import com.clinicahospital.connection.ComandosManager;
import com.clinicahospital.pessoas.Pessoa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Weleson
 */
public class Tela_Agenda extends javax.swing.JFrame {
    int nivel_acesso;
    int id_agenda;
    Agendar agenda;
    /**
     * Creates new form Tela_Inicio
     * @param nivel_acesso
     */
    public Tela_Agenda(int nivel_acesso) {
        initComponents();
        botao_Informs.setEnabled(false);
        botao_desmarcar.setEnabled(false);
        this.nivel_acesso = nivel_acesso;
        System.out.println(nivel_acesso);
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        AgendaManager agenda = new AgendaManager();
        List<Agendar> agendas = new ArrayList<Agendar>();
        agendas = agenda.listar();
        for(int i = 0; i < agendas.size(); i++){
            Agendar aaux = new Agendar();
            aaux = agendas.get(i);
            Object[] dados = {aaux.getId(), aaux.getData(), aaux.getHorario(), aaux.getId_medico(), aaux.getId_paciente()};
            tabela.addRow(dados);
        }
    }
    
    public Tela_Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastro = new javax.swing.JButton();
        botao_desmarcar = new javax.swing.JButton();
        botao_agenda = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        botao_Informs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastro.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastro.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastro.setText("Cadastro");
        getContentPane().add(botao_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 150, 50));

        botao_desmarcar.setBackground(new java.awt.Color(86, 131, 176));
        botao_desmarcar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_desmarcar.setForeground(new java.awt.Color(255, 255, 255));
        botao_desmarcar.setText("Desmarcar");
        botao_desmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_desmarcarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_desmarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 150, 50));

        botao_agenda.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda.setText("Agendar");
        botao_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agendaActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 150, 50));

        botao_Informs.setBackground(new java.awt.Color(86, 131, 176));
        botao_Informs.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_Informs.setForeground(new java.awt.Color(255, 255, 255));
        botao_Informs.setText("Ver Mais");
        botao_Informs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_InformsActionPerformed(evt);
            }
        });
        getContentPane().add(botao_Informs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 150, 50));

        jTable1.setBackground(new java.awt.Color(86, 131, 176));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DATA", "HORA", "MEDICO", "PACIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 770, 520));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 255, 255));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo.png"))); // NOI18N
        icone.setText("HAE");
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 60));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        Tela_Menu tela = new Tela_Menu(nivel_acesso);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    private void botao_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agendaActionPerformed
        Tela_Agendar agenda = new Tela_Agendar();
        agenda.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_agendaActionPerformed

    private void botao_InformsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_InformsActionPerformed
        Info_Pacientes pacientes = new Info_Pacientes(agenda.getId(), agenda.getId_paciente(), agenda.getData(), agenda.getHorario());
        pacientes.setVisible(true);
        
    }//GEN-LAST:event_botao_InformsActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        botao_Informs.setEnabled(true);
        botao_desmarcar.setEnabled(true);
        int linha = jTable1.getSelectedRow();
        Agendar agendaAux = new Agendar();
        agendaAux.setData(String.valueOf(jTable1.getValueAt(linha, 1)));
        agendaAux.setHorario(String.valueOf(jTable1.getValueAt(linha, 2)));
        agendaAux.setId(Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 0))));
        agendaAux.setId_medico(Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 3))));
        agendaAux.setId_paciente(Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 4))));
        this.agenda = agendaAux;
    }//GEN-LAST:event_jTable1MouseClicked

    private void botao_desmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_desmarcarActionPerformed
        int linha = jTable1.getSelectedRow();
        id_agenda =  Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 0)));
        AgendaManager agenda = new AgendaManager();
        try {
            agenda.deletar(id_agenda);
            JOptionPane.showMessageDialog(null, "Consulta desmarcada com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Agenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_Agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botao_desmarcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_Informs;
    private javax.swing.JButton botao_agenda;
    private javax.swing.JButton botao_cadastro;
    private javax.swing.JButton botao_desmarcar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
