/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Weleson
 */
public class Tela_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_entrar1 = new javax.swing.JButton();
        botao_entrar = new javax.swing.JButton();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_entrar1.setBackground(new java.awt.Color(86, 131, 176));
        botao_entrar1.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_entrar1.setForeground(new java.awt.Color(255, 255, 255));
        botao_entrar1.setText("Entrar");
        botao_entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao_entrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 150, 50));

        botao_entrar.setBackground(new java.awt.Color(86, 131, 176));
        botao_entrar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_entrar.setForeground(new java.awt.Color(255, 255, 255));
        botao_entrar.setText("Cadastrar");
        botao_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_entrarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 150, 50));

        icone.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(86, 131, 176));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-2.png"))); // NOI18N
        icone.setText("HAE");
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 70));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-Escolha-Médico-Secretário.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrar1ActionPerformed
        Tela_login login = new Tela_login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_entrar1ActionPerformed

    private void botao_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_entrarActionPerformed
        Tela_Ecolher escolha = new Tela_Ecolher();
        escolha.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_entrar;
    private javax.swing.JButton botao_entrar1;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    // End of variables declaration//GEN-END:variables
}
