/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.clinicahospital.connection.ComandosManager;
import com.clinicahospital.connection.ContasManager;
import com.clinicahospital.connection.MedicoManager;
import com.clinicahospital.connection.PessoaManager;
import com.clinicahospital.pessoas.Contas;
import com.clinicahospital.pessoas.Medico;
import com.clinicahospital.pessoas.Pessoa;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Weleson
 */
public class Tela_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastrar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        campo_sobrenome = new javax.swing.JTextField();
        campo_telefone = new javax.swing.JTextField();
        campo_crm = new javax.swing.JTextField();
        campo_senha = new javax.swing.JTextField();
        icone1 = new javax.swing.JLabel();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastrar.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastrar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastrar.setText("Cadastrar");
        botao_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 150, 50));

        campo_nome.setBackground(new java.awt.Color(255, 255, 255));
        campo_nome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_nome.setText("Nome");
        campo_nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_nomeMouseClicked(evt);
            }
        });
        getContentPane().add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, 40));

        campo_sobrenome.setBackground(new java.awt.Color(255, 255, 255));
        campo_sobrenome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_sobrenome.setText("Sobrenome");
        campo_sobrenome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_sobrenome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_sobrenomeMouseClicked(evt);
            }
        });
        getContentPane().add(campo_sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 350, 40));

        campo_telefone.setBackground(new java.awt.Color(255, 255, 255));
        campo_telefone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_telefone.setText("Telefone");
        campo_telefone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_telefoneMouseClicked(evt);
            }
        });
        getContentPane().add(campo_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 350, 40));

        campo_crm.setBackground(new java.awt.Color(255, 255, 255));
        campo_crm.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_crm.setText("CRM");
        campo_crm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_crm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_crmMouseClicked(evt);
            }
        });
        getContentPane().add(campo_crm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 350, 40));

        campo_senha.setBackground(new java.awt.Color(255, 255, 255));
        campo_senha.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_senha.setText("Senha");
        campo_senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(86, 131, 176)));
        campo_senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_senhaMouseClicked(evt);
            }
        });
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 350, 40));

        icone1.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 20)); // NOI18N
        icone1.setForeground(new java.awt.Color(86, 131, 176));
        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-2.png"))); // NOI18N
        icone1.setText("HAE");
        getContentPane().add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 70));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 51, 51));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Médico.png"))); // NOI18N
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 170, 160));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vyghyjkghkghk.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    private void botao_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarActionPerformed
        try {                                                
            MedicoManager medicoCad = new MedicoManager();
            Medico medico = new Medico(campo_nome.getText(), campo_sobrenome.getText(), campo_telefone.getText(), "Vazio", "Vazio", "Vazio", "Vazio", 2, Integer.parseInt(campo_crm.getText()));
            System.out.println(medico.getNome());
            medicoCad.inserir(medico);
            
            ContasManager contasCad = new ContasManager();
            Contas conta = new Contas();
            Medico paux = medicoCad.selecionar(campo_telefone.getText());
            conta.setId_conta(paux.getId());
            conta.setLogin(campo_crm.getText());
            conta.setSenha(campo_senha.getText());
            conta.setNivel_acesso(2);
            try {
                contasCad.cadastrar(conta);
                JOptionPane.showMessageDialog(null, "Sua conta é: " + conta.getLogin() + " E sua senha é: " + conta.getSenha());
                Tela_Inicio inicio = new Tela_Inicio();
                inicio.setVisible(true);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_cadastro1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Tela_cadastro1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Tela_cadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela_cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botao_cadastrarActionPerformed

    private void campo_nomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_nomeMouseClicked
        campo_nome.setText("");
    }//GEN-LAST:event_campo_nomeMouseClicked

    private void campo_sobrenomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_sobrenomeMouseClicked
        campo_sobrenome.setText("");
    }//GEN-LAST:event_campo_sobrenomeMouseClicked

    private void campo_telefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_telefoneMouseClicked
        campo_telefone.setText("");
    }//GEN-LAST:event_campo_telefoneMouseClicked

    private void campo_crmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_crmMouseClicked
        campo_crm.setText("");
    }//GEN-LAST:event_campo_crmMouseClicked

    private void campo_senhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_senhaMouseClicked
        campo_senha.setText("");
    }//GEN-LAST:event_campo_senhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastrar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_crm;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_senha;
    private javax.swing.JTextField campo_sobrenome;
    private javax.swing.JTextField campo_telefone;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel icone1;
    // End of variables declaration//GEN-END:variables
}
