/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Weleson
 */
public class Tela_Ecolher extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Ecolher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_medico = new javax.swing.JButton();
        botao_secretario = new javax.swing.JButton();
        icone1 = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_medico.setBackground(new java.awt.Color(86, 131, 176));
        botao_medico.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_medico.setForeground(new java.awt.Color(255, 255, 255));
        botao_medico.setText("Médico");
        botao_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_medicoActionPerformed(evt);
            }
        });
        getContentPane().add(botao_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 150, 50));

        botao_secretario.setBackground(new java.awt.Color(86, 131, 176));
        botao_secretario.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_secretario.setForeground(new java.awt.Color(255, 255, 255));
        botao_secretario.setText("Secretário");
        botao_secretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_secretarioActionPerformed(evt);
            }
        });
        getContentPane().add(botao_secretario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 160, 50));

        icone1.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 20)); // NOI18N
        icone1.setForeground(new java.awt.Color(86, 131, 176));
        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-2.png"))); // NOI18N
        icone1.setText("HAE");
        getContentPane().add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 70));

        mensagem.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        mensagem.setForeground(new java.awt.Color(255, 51, 51));
        mensagem.setText("Deseja se cadastrar como:");
        getContentPane().add(mensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 310, 80));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-Escolha-Médico-Secretário.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_medicoActionPerformed
        Tela_cadastro tela = new Tela_cadastro();
        tela.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_botao_medicoActionPerformed

    private void botao_secretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_secretarioActionPerformed
        Tela_cadastro1 secretaria = new Tela_cadastro1(2, 2);
        secretaria.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_secretarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Ecolher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Ecolher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Ecolher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Ecolher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Ecolher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_medico;
    private javax.swing.JButton botao_secretario;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone1;
    private javax.swing.JLabel mensagem;
    // End of variables declaration//GEN-END:variables
}
