/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Weleson
 */
public class Tela_Menu3 extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Menu3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastro = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        campo_nome = new javax.swing.JTextField();
        medico = new javax.swing.JComboBox<>();
        campo_senha = new javax.swing.JTextField();
        campo_receita = new javax.swing.JTextField();
        campo_descricao = new javax.swing.JTextField();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        icone1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastro.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastro.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastro.setText("Cadastrar");
        getContentPane().add(botao_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 150, 50));

        campo_nome.setBackground(new java.awt.Color(142, 193, 245));
        campo_nome.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_nome.setForeground(new java.awt.Color(255, 255, 255));
        campo_nome.setText("Nome");
        campo_nome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(campo_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 350, 40));

        medico.setBackground(new java.awt.Color(142, 193, 245));
        medico.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        medico.setForeground(new java.awt.Color(255, 255, 255));
        medico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        medico.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 350, 40));

        campo_senha.setBackground(new java.awt.Color(142, 193, 245));
        campo_senha.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_senha.setForeground(new java.awt.Color(255, 255, 255));
        campo_senha.setText("Data");
        campo_senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(campo_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 350, 40));

        campo_receita.setBackground(new java.awt.Color(142, 193, 245));
        campo_receita.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_receita.setForeground(new java.awt.Color(255, 255, 255));
        campo_receita.setText("Receita");
        campo_receita.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(campo_receita, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 350, 40));

        campo_descricao.setBackground(new java.awt.Color(142, 193, 245));
        campo_descricao.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_descricao.setForeground(new java.awt.Color(255, 255, 255));
        campo_descricao.setText("Descrição");
        campo_descricao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(campo_descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 350, 110));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 255, 255));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo.png"))); // NOI18N
        icone.setText("HAE");
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 60));

        fundo.setForeground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        icone1.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone1.setForeground(new java.awt.Color(255, 255, 255));
        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo.png"))); // NOI18N
        icone1.setText("HAE");
        getContentPane().add(icone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Menu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cadastro;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_descricao;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_receita;
    private javax.swing.JTextField campo_senha;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel icone1;
    private javax.swing.JComboBox<String> medico;
    // End of variables declaration//GEN-END:variables
}
