/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.clinicahospital.connection.ContasManager;
import com.clinicahospital.connection.PessoaManager;
import com.clinicahospital.pessoas.Contas;
import com.clinicahospital.pessoas.Pessoa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Weleson
 */
public class Tela_Contas extends javax.swing.JFrame {
    int nivel_acesso;
    Contas contaAux = new Contas();
    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Contas() {
        initComponents();
    }
    public Tela_Contas(int nivel_acesso) {
        initComponents();
        botao_agenda2.setEnabled(false);
        campo_busca1.setVisible(false);
        botao_agenda3.setVisible(false);
        this.nivel_acesso = nivel_acesso;
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        ContasManager contasTab = new ContasManager();
        List<Contas> contas = new ArrayList<Contas>();
        contas = contasTab.listar();
        for(int i = 0; i < contas.size(); i++){
            Contas caux = contas.get(i);
            Object[] dados = {caux.getId(), caux.getId_conta(), caux.getLogin(), caux.getSenha(), caux.getNivel_acesso()};
            tabela.addRow(dados);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_agenda = new javax.swing.JButton();
        botao_agenda1 = new javax.swing.JButton();
        botao_agenda2 = new javax.swing.JButton();
        botao_agenda3 = new javax.swing.JButton();
        botao_agenda4 = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        campo_busca1 = new javax.swing.JTextField();
        campo_busca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        icone = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_agenda.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda.setText("Cadastrar");
        botao_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agendaActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 150, 50));

        botao_agenda1.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda1.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda1.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda1.setText("Agendar");
        botao_agenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agenda1ActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 150, 50));

        botao_agenda2.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda2.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda2.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda2.setText("Remover Acesso");
        botao_agenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agenda2ActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 310, 50));

        botao_agenda3.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda3.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda3.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda3.setText("Ok");
        botao_agenda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agenda3ActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 60, 50));

        botao_agenda4.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda4.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda4.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda4.setText("Mudar Senha");
        botao_agenda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agenda4ActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 240, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 150, 50));

        campo_busca1.setBackground(new java.awt.Color(142, 193, 245));
        campo_busca1.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_busca1.setForeground(new java.awt.Color(255, 255, 255));
        campo_busca1.setText("Nova Senha");
        campo_busca1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        campo_busca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_busca1MouseClicked(evt);
            }
        });
        campo_busca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_busca1ActionPerformed(evt);
            }
        });
        getContentPane().add(campo_busca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 350, 40));

        campo_busca.setBackground(new java.awt.Color(142, 193, 245));
        campo_busca.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        campo_busca.setForeground(new java.awt.Color(255, 255, 255));
        campo_busca.setText("Pesquisar");
        campo_busca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        campo_busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campo_buscaMouseClicked(evt);
            }
        });
        campo_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_buscaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 350, 40));

        jTable1.setBackground(new java.awt.Color(86, 131, 176));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Perfil", "Login", "Senha", "Nível"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 770, 520));

        icone.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        icone.setForeground(new java.awt.Color(255, 255, 255));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo.png"))); // NOI18N
        icone.setText("HAE");
        getContentPane().add(icone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 170, 60));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_buscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_buscaMouseClicked
        campo_busca.setText("");
    }//GEN-LAST:event_campo_buscaMouseClicked

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        Tela_Menu menu = new Tela_Menu(nivel_acesso);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    private void campo_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_buscaActionPerformed
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        PessoaManager pessoaEspec = new PessoaManager();
        List<Pessoa> pessoas = new ArrayList<Pessoa>();
        pessoas = pessoaEspec.selecionar(campo_busca.getText());
        int tamanho = tabela.getRowCount();
        for(int i = 0; i < tamanho; i++){
            tabela.removeRow(i);
        }
        for(int i = 0; i < pessoas.size(); i++){
            
            Pessoa paux = pessoas.get(i);
            Object[] dados = {paux.getId(), paux.getNome(), paux.getSobrenome(), paux.getTelefone(), paux.getEndereco(), paux.getDoencas(), paux.getNascimento(), paux.getConvenio()};
            tabela.addRow(dados);
        }
        
    }//GEN-LAST:event_campo_buscaActionPerformed

    private void botao_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agendaActionPerformed
        Tela_cadastro1 cadastrar = new Tela_cadastro1(1,nivel_acesso);
        cadastrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_agendaActionPerformed

    private void botao_agenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agenda1ActionPerformed
        int linha = jTable1.getSelectedRow();
        
        Tela_Agendar tela = new Tela_Agendar(nivel_acesso, Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 0))), String.valueOf(jTable1.getValueAt(linha, 1)));
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_agenda1ActionPerformed

    private void botao_agenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agenda2ActionPerformed
        ContasManager contas = new ContasManager();
        contaAux.setNivel_acesso(0);
        contas.atualizar(contaAux);
        JOptionPane.showMessageDialog(null, "Acesso removido com sucesso!");
        
                
    }//GEN-LAST:event_botao_agenda2ActionPerformed

    private void campo_busca1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo_busca1MouseClicked
        campo_busca1.setText("");
    }//GEN-LAST:event_campo_busca1MouseClicked

    private void campo_busca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_busca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_busca1ActionPerformed

    private void botao_agenda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agenda3ActionPerformed
        campo_busca1.setVisible(false);
        botao_agenda3.setVisible(false);
        botao_agenda4.setVisible(true);
        ContasManager contas = new ContasManager();
        contaAux.setSenha(String.valueOf(campo_busca1.getText()));
        contas.atualizar(contaAux);
        JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
    }//GEN-LAST:event_botao_agenda3ActionPerformed

    private void botao_agenda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agenda4ActionPerformed
        campo_busca1.setVisible(true);
        botao_agenda3.setVisible(true);
        botao_agenda4.setVisible(false);
    }//GEN-LAST:event_botao_agenda4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Contas conta_aux = new Contas();
        int linha = jTable1.getSelectedRow();
        contaAux.setId(Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 0))));
        contaAux.setId_conta(Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 1))));
        contaAux.setLogin((String.valueOf(jTable1.getValueAt(linha, 2))));
        contaAux.setSenha(String.valueOf(jTable1.getValueAt(linha, 3)));
        contaAux.setNivel_acesso(Integer.parseInt(String.valueOf(jTable1.getValueAt(linha, 4))));
        botao_agenda2.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Contas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Contas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_agenda;
    private javax.swing.JButton botao_agenda1;
    private javax.swing.JButton botao_agenda2;
    private javax.swing.JButton botao_agenda3;
    private javax.swing.JButton botao_agenda4;
    private javax.swing.JButton botao_sair;
    private javax.swing.JTextField campo_busca;
    private javax.swing.JTextField campo_busca1;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
