/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Weleson
 */
public class Tela_Menu extends javax.swing.JFrame {
    int nivel_acesso;
    /**
     * Creates new form Tela_Inicio
     */
    public Tela_Menu() {
        initComponents();
    }
    public Tela_Menu(int nivel_acesso){
        initComponents();
        
        this.nivel_acesso = nivel_acesso;
        System.out.println(nivel_acesso);
        switch(nivel_acesso){
            case 0:
                botao_agenda.setEnabled(false);
                botao_consulta.setEnabled(false);
                botao_cadastro.setEnabled(false);
                botao_pacientes.setEnabled(false);
                botao_gerenciar.setEnabled(false);
                botao_mensagens.setEnabled(false);
                break;
            case 1:
                botao_consulta.setEnabled(false);
                botao_gerenciar.setEnabled(false);
                break;
            case 2:
                botao_consulta.setEnabled(true);
                break;
            default:
                botao_consulta.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_cadastro = new javax.swing.JButton();
        botao_mensagens = new javax.swing.JButton();
        botao_pacientes = new javax.swing.JButton();
        botao_consulta = new javax.swing.JButton();
        botao_agenda = new javax.swing.JButton();
        botao_gerenciar = new javax.swing.JButton();
        botao_sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_cadastro.setBackground(new java.awt.Color(86, 131, 176));
        botao_cadastro.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_cadastro.setForeground(new java.awt.Color(255, 255, 255));
        botao_cadastro.setText("Cadastro");
        botao_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(botao_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 50));

        botao_mensagens.setBackground(new java.awt.Color(86, 131, 176));
        botao_mensagens.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_mensagens.setForeground(new java.awt.Color(255, 255, 255));
        botao_mensagens.setText("Mensagens");
        botao_mensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_mensagensActionPerformed(evt);
            }
        });
        getContentPane().add(botao_mensagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 150, 50));

        botao_pacientes.setBackground(new java.awt.Color(86, 131, 176));
        botao_pacientes.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_pacientes.setForeground(new java.awt.Color(255, 255, 255));
        botao_pacientes.setText("Pacientes");
        botao_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_pacientesActionPerformed(evt);
            }
        });
        getContentPane().add(botao_pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 150, 50));

        botao_consulta.setBackground(new java.awt.Color(86, 131, 176));
        botao_consulta.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_consulta.setForeground(new java.awt.Color(255, 255, 255));
        botao_consulta.setText("Consulta");
        botao_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(botao_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 50));

        botao_agenda.setBackground(new java.awt.Color(86, 131, 176));
        botao_agenda.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_agenda.setForeground(new java.awt.Color(255, 255, 255));
        botao_agenda.setText("Agenda");
        botao_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_agendaActionPerformed(evt);
            }
        });
        getContentPane().add(botao_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 150, 50));

        botao_gerenciar.setBackground(new java.awt.Color(86, 131, 176));
        botao_gerenciar.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_gerenciar.setForeground(new java.awt.Color(255, 255, 255));
        botao_gerenciar.setText("Contas");
        botao_gerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_gerenciarActionPerformed(evt);
            }
        });
        getContentPane().add(botao_gerenciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 150, 50));

        botao_sair.setBackground(new java.awt.Color(86, 131, 176));
        botao_sair.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        botao_sair.setForeground(new java.awt.Color(255, 255, 255));
        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 150, 50));

        jLabel3.setFont(new java.awt.Font("Source Code Pro", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo.png"))); // NOI18N
        jLabel3.setText("HAE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 170, 60));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela-Inicial.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1200, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
        Tela_Inicio inicio = new Tela_Inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_sairActionPerformed

    private void botao_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_agendaActionPerformed
        Tela_Agenda agenda = new Tela_Agenda(nivel_acesso);
        agenda.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_agendaActionPerformed

    private void botao_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastroActionPerformed
        Tela_cadastro1 tela = new Tela_cadastro1(1, nivel_acesso);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_cadastroActionPerformed

    private void botao_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_pacientesActionPerformed
        Tela_Pacientes paciente = new Tela_Pacientes(nivel_acesso);
        paciente.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_pacientesActionPerformed

    private void botao_gerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_gerenciarActionPerformed
        Tela_Contas conta = new Tela_Contas(nivel_acesso);
        conta.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_gerenciarActionPerformed

    private void botao_mensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_mensagensActionPerformed
        Tela_Login_Mensagens loginMensagens = new Tela_Login_Mensagens();
        loginMensagens.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_mensagensActionPerformed

    private void botao_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_consultaActionPerformed
        Tela_Consulta consulta = new Tela_Consulta(nivel_acesso);
        consulta.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao_consultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_agenda;
    private javax.swing.JButton botao_cadastro;
    private javax.swing.JButton botao_consulta;
    private javax.swing.JButton botao_gerenciar;
    private javax.swing.JButton botao_mensagens;
    private javax.swing.JButton botao_pacientes;
    private javax.swing.JButton botao_sair;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
